paths:  
  raw_data: data/census.csv
  preprocessed_data: data/census_cln.csv
  test_data: data/census_test.csv
  label_encoder: model/label_encoder.pkl
  pretrained_model: model/pretrained_model.pkl
  
feature_engineering:
  categorical_cols:
    - workclass
    - education
    - marital-status
    - occupation
    - relationship
    - race
    - sex
    - native-country
  target_label_col: salary

modelling:
  test_size: 0.2
  random_seed: 10
  cv: 5           # number of folds in cross-validation
  rf_params_grid: # parameters grid for hyper-parameter tuning via GridSearchCV
    n_estimators: [50, 100, 200, 500]
    max_depth: [5, 7, 10]
    min_samples_split: [50]
    min_samples_leaf: [20]
    class_weight: ['balanced']

evaluation:
  slicing_cols: # subset of categorical columns
    - workclass
    - education
    - marital-status
    - race
    - sex
  parity_metric: FNR # One of the following: 'FDR', 'FPR', 'FOR', 'FNR', 'TPR', 'TNR', 'NPV'